[build]
builder = "nixpacks"

[deploy]
startCommand = "pip install -r requirements.txt && python main.py"
healthcheckPath = "/"
healthcheckTimeout = 100

[[buildpacks]]
uri = "https://github.com/heroku/heroku-buildpack-google-chrome"